### ISSUE TITLE
テストが一部実行されない

### ISSUE THREAD

**Issue by youpong** [mattn/go-gimei#3]
## Describe the bug

テストの一部(ExampleGimeiName)が実行されない。

## 再現手順

-v オプションを指定して go test を実行する。 ExampleGimeiName を含まない。

```bash
$ go test -v
=== RUN   ExampleGimeiAddress
--- PASS: ExampleGimeiAddress (0.04s)
PASS
ok  	github.com/mattn/go-gimei	0.045s
```

## 期待した振る舞い

以下のように ExampleGimeiName を含むことが期待される。

```bash
$ go test -v
=== RUN   ExampleGimeiName
--- PASS: ExampleGimeiName (0.14s)
=== RUN   ExampleGimeiAddress
--- PASS: ExampleGimeiAddress (0.04s)
PASS
ok  	github.com/mattn/go-gimei	0.188s
```

## 再現した環境

- Ubuntu-20.04.3 LTS/
- go version go1.13.8 linux/amd64

**Comment by mattn** [comment]
ありがとうございます。PR 頂けたらマージします。
